/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Control {
  'id' : string,
  'controlName' : [] | [string],
  'controlType' : string,
  'radioOptions' : [] | [Array<string>],
  'radioGroupIsVertical' : [] | [boolean],
  'sliderIsVertical' : [] | [boolean],
  'binaryCode' : string,
}
export interface Event {
  'controlName' : [] | [string],
  'controlType' : string,
  'value' : string,
  'controlId' : string,
  'timestamp' : Time,
  'binaryCode' : string,
}
export interface Layout { 'controls' : Array<Control> }
export type Time = bigint;
export interface _SERVICE {
  'backendScaffoldPlaceholderFunction' : ActorMethod<[], string>,
  'emitEvent' : ActorMethod<
    [string, string, [] | [string], string, string],
    undefined
  >,
  'emitHatGpiosetEvent' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'getEventsByControlId' : ActorMethod<[string], Array<Event>>,
  'getLayout' : ActorMethod<[], Layout>,
  'getRecentEvents' : ActorMethod<[], Array<Event>>,
  'saveLayout' : ActorMethod<[Layout], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];