/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Event = IDL.Record({
  'controlType' : IDL.Text,
  'value' : IDL.Text,
  'controlId' : IDL.Text,
  'timestamp' : Time,
  'binaryCode' : IDL.Text,
});
export const Control = IDL.Record({
  'id' : IDL.Text,
  'controlType' : IDL.Text,
  'radioOptions' : IDL.Opt(IDL.Vec(IDL.Text)),
  'binaryCode' : IDL.Text,
});
export const Layout = IDL.Record({ 'controls' : IDL.Vec(Control) });

export const idlService = IDL.Service({
  'emitEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getEventsByControlId' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getLayout' : IDL.Func([], [Layout], ['query']),
  'getRecentEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'saveLayout' : IDL.Func([Layout], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Event = IDL.Record({
    'controlType' : IDL.Text,
    'value' : IDL.Text,
    'controlId' : IDL.Text,
    'timestamp' : Time,
    'binaryCode' : IDL.Text,
  });
  const Control = IDL.Record({
    'id' : IDL.Text,
    'controlType' : IDL.Text,
    'radioOptions' : IDL.Opt(IDL.Vec(IDL.Text)),
    'binaryCode' : IDL.Text,
  });
  const Layout = IDL.Record({ 'controls' : IDL.Vec(Control) });
  
  return IDL.Service({
    'emitEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getEventsByControlId' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getLayout' : IDL.Func([], [Layout], ['query']),
    'getRecentEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'saveLayout' : IDL.Func([Layout], [], []),
  });
};

export const init = ({ IDL }) => { return []; };