/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Event = IDL.Record({
  'controlName' : IDL.Opt(IDL.Text),
  'controlType' : IDL.Text,
  'decimalCode' : IDL.Nat,
  'value' : IDL.Text,
  'commandStr' : IDL.Text,
  'codeType' : IDL.Text,
  'controlId' : IDL.Text,
  'timestamp' : Time,
});
export const Control = IDL.Record({
  'id' : IDL.Text,
  'decimalCodeLeft' : IDL.Opt(IDL.Nat),
  'controlName' : IDL.Opt(IDL.Text),
  'controlType' : IDL.Text,
  'decimalCode' : IDL.Nat,
  'radioOptions' : IDL.Opt(IDL.Vec(IDL.Text)),
  'radioGroupIsVertical' : IDL.Opt(IDL.Bool),
  'decimalCodeRight' : IDL.Opt(IDL.Nat),
  'sliderIsVertical' : IDL.Opt(IDL.Bool),
  'decimalCodeOn' : IDL.Opt(IDL.Nat),
  'decimalCodeUp' : IDL.Opt(IDL.Nat),
  'decimalCodeOff' : IDL.Opt(IDL.Nat),
  'decimalCodeDown' : IDL.Opt(IDL.Nat),
});
export const Layout = IDL.Record({ 'controls' : IDL.Vec(Control) });

export const idlService = IDL.Service({
  'backendScaffoldPlaceholderFunction' : IDL.Func([], [IDL.Text], ['query']),
  'emitButtonEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'getEventsByControlId' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getLayout' : IDL.Func([], [Layout], ['query']),
  'getRecentEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'saveLayout' : IDL.Func([Layout], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Event = IDL.Record({
    'controlName' : IDL.Opt(IDL.Text),
    'controlType' : IDL.Text,
    'decimalCode' : IDL.Nat,
    'value' : IDL.Text,
    'commandStr' : IDL.Text,
    'codeType' : IDL.Text,
    'controlId' : IDL.Text,
    'timestamp' : Time,
  });
  const Control = IDL.Record({
    'id' : IDL.Text,
    'decimalCodeLeft' : IDL.Opt(IDL.Nat),
    'controlName' : IDL.Opt(IDL.Text),
    'controlType' : IDL.Text,
    'decimalCode' : IDL.Nat,
    'radioOptions' : IDL.Opt(IDL.Vec(IDL.Text)),
    'radioGroupIsVertical' : IDL.Opt(IDL.Bool),
    'decimalCodeRight' : IDL.Opt(IDL.Nat),
    'sliderIsVertical' : IDL.Opt(IDL.Bool),
    'decimalCodeOn' : IDL.Opt(IDL.Nat),
    'decimalCodeUp' : IDL.Opt(IDL.Nat),
    'decimalCodeOff' : IDL.Opt(IDL.Nat),
    'decimalCodeDown' : IDL.Opt(IDL.Nat),
  });
  const Layout = IDL.Record({ 'controls' : IDL.Vec(Control) });
  
  return IDL.Service({
    'backendScaffoldPlaceholderFunction' : IDL.Func([], [IDL.Text], ['query']),
    'emitButtonEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getEventsByControlId' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getLayout' : IDL.Func([], [Layout], ['query']),
    'getRecentEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'saveLayout' : IDL.Func([Layout], [], []),
  });
};

export const init = ({ IDL }) => { return []; };