/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Control {
    id: string;
    controlType: string;
    radioOptions?: Array<string>;
    radioGroupIsVertical?: boolean;
    binaryCode: string;
}
export interface Layout {
    controls: Array<Control>;
}
export interface Event {
    controlType: string;
    value: string;
    controlId: string;
    timestamp: Time;
    binaryCode: string;
}
export interface backendInterface {
    emitEvent(controlId: string, controlType: string, value: string, binaryCode: string): Promise<void>;
    getEventsByControlId(controlId: string): Promise<Array<Event>>;
    getLayout(): Promise<Layout>;
    getRadioGroupLayout(): Promise<boolean>;
    getRecentEvents(): Promise<Array<Event>>;
    saveLayout(layout: Layout): Promise<void>;
}
import type { Control as _Control, Layout as _Layout } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async emitEvent(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.emitEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emitEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getEventsByControlId(arg0: string): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByControlId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByControlId(arg0);
            return result;
        }
    }
    async getLayout(): Promise<Layout> {
        if (this.processError) {
            try {
                const result = await this.actor.getLayout();
                return from_candid_Layout_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLayout();
            return from_candid_Layout_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRadioGroupLayout(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getRadioGroupLayout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRadioGroupLayout();
            return result;
        }
    }
    async getRecentEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentEvents();
            return result;
        }
    }
    async saveLayout(arg0: Layout): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLayout(to_candid_Layout_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLayout(to_candid_Layout_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Control_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Control): Control {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Layout_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Layout): Layout {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    controls: Array<_Control>;
}): {
    controls: Array<Control>;
} {
    return {
        controls: from_candid_vec_n3(_uploadFile, _downloadFile, value.controls)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    controlType: string;
    radioOptions: [] | [Array<string>];
    radioGroupIsVertical: [] | [boolean];
    binaryCode: string;
}): {
    id: string;
    controlType: string;
    radioOptions?: Array<string>;
    radioGroupIsVertical?: boolean;
    binaryCode: string;
} {
    return {
        id: value.id,
        controlType: value.controlType,
        radioOptions: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.radioOptions)),
        radioGroupIsVertical: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.radioGroupIsVertical)),
        binaryCode: value.binaryCode
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Control>): Array<Control> {
    return value.map((x)=>from_candid_Control_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Control_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Control): _Control {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Layout_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Layout): _Layout {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    controlType: string;
    radioOptions?: Array<string>;
    radioGroupIsVertical?: boolean;
    binaryCode: string;
}): {
    id: string;
    controlType: string;
    radioOptions: [] | [Array<string>];
    radioGroupIsVertical: [] | [boolean];
    binaryCode: string;
} {
    return {
        id: value.id,
        controlType: value.controlType,
        radioOptions: value.radioOptions ? candid_some(value.radioOptions) : candid_none(),
        radioGroupIsVertical: value.radioGroupIsVertical ? candid_some(value.radioGroupIsVertical) : candid_none(),
        binaryCode: value.binaryCode
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    controls: Array<Control>;
}): {
    controls: Array<_Control>;
} {
    return {
        controls: to_candid_vec_n10(_uploadFile, _downloadFile, value.controls)
    };
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Control>): Array<_Control> {
    return value.map((x)=>to_candid_Control_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
